[[plugins]]
repo = 'rhysd/vim-clang-format'
hook_add = '''
    let g:clang_format#style_options = {
        \ "AccessModifierOffset" : -4,
        \ "IndentWidth" : 4,
        \ "TabWidth" : 4,
        \ "UseTab" : "Never",
        \ "Standard" : "C++11",
        \ "AllowShortBlocksOnASingleLine" : "true",
        \ "AllowShortIfStatementsOnASingleLine" : "true",
        \ "AllowShortCaseLabelsOnASingleLine" : "true"}
    let g:clang_format#auto_format = 1
'''

[[plugins]]
repo = 'zchee/deoplete-clang'
hook_add = '''
    let g:deoplete#sources#clang#clang_header='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang'
    let g:deoplete#sources#clang#libclang_path='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib'
'''

