[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    function! NERDTreeToggleEnhanced()
        if g:NERDTree.IsOpen() && winnr() != g:NERDTree.GetWinNum()
            call g:NERDTree.CursorToTreeWin()
        else
            :NERDTreeToggle
        endif
    endfunction
    nnoremap <silent><C-e> :call NERDTreeToggleEnhanced()<CR>
'''

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'rhysd/accelerated-jk'
hook_add = '''
    nmap j <Plug>(accelerated_jk_gj)
    nmap k <Plug>(accelerated_jk_gk)
'''

