[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/vimshell.vim'

[[plugins]]
repo = 'vim-syntastic/syntastic'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
    let g:quickrun_config={}
    let g:quickrun_config["cpp"] = {
        \ "type" : "cpp",
        \ "command" : "clang++",
        \ "cmdopt" : " -std=c++14",
        \ "runner" : "vimproc",
        \ "runner/vimproc/updatetime" : 100}
    let g:quickrun_config["_"] = {
        \ "outputter/buffer/split" : ":rightbelow 8sp"}
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    function! NERDTreeToggleEnhanced()
        if g:NERDTree.IsOpen() && winnr() != g:NERDTree.GetWinNum()
            call g:NERDTree.CursorToTreeWin()
        else
            :NERDTreeToggle
        endif
    endfunction
    nnoremap <silent><C-e> :call NERDTreeToggleEnhanced()<CR>
'''

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'rhysd/accelerated-jk'
hook_add = '''
    nmap j <Plug>(accelerated_jk_gj)
    nmap k <Plug>(accelerated_jk_gk)
'''

