[[plugins]]
repo = 'rhysd/vim-clang-format'
on_ft = ['c', 'cpp', 'cuda']
hook_add = '''
    let g:clang_format#style_options = {
        \ "BasedOnStyle" : "Google",
        \ "AccessModifierOffset" : -2,
        \ "IndentWidth" : 2,
        \ "TabWidth" : 2,
        \ "UseTab" : "Never",
        \ "Standard" : "C++11",
        \ "ColumnLimit" : 100,
        \ "AllowShortBlocksOnASingleLine" : "true",
        \ "AllowShortIfStatementsOnASingleLine" : "true",
        \ "AllowShortCaseLabelsOnASingleLine" : "true"}
    let g:clang_format#auto_format = 1
    autocmd FileType c setlocal sw=2 sts=2 ts=2 et
'''

[[plugins]]
repo = 'tell-k/vim-autopep8'
on_ft = ['python']
hook_add = '''
    let g:autopep8_on_save = 1
    let g:autopep8_disable_show_diff=1
'''

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_add = '''
let g:rustfmt_autosave = 1
'''

