[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'rhysd/vim-clang-format'
on_ft = ['cpp', 'h']
hook_add = '''
    let g:clang_format#style_options = {
        \ "AccessModifierOffset" : -4,
        \ "IndentWidth" : 4,
        \ "TabWidth" : 4,
        \ "Standard" : "C++11",
        \ "AllowShortBlocksOnASingleLine" : "true",
        \ "AllowShortIfStatementsOnASingleLine" : "true"}
    map <C-k><C-d> :ClangFormat<cr>
'''

[[plugins]]
repo = 'justmao945/vim-clang'
on_ft = ['cpp', 'h']
hook_add = '''
    let g:clang_cpp_options = '-std=c++14 -stdlib=libc++'
    map <C-c><C-c> :ClangSyntaxCheck<cr>
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    function! NERDTreeToggleEnhanced()
        if g:NERDTree.IsOpen() && winnr() != g:NERDTree.GetWinNum()
            call g:NERDTree.CursorToTreeWin()
        else
            :NERDTreeToggle
        endif
    endfunction
    nnoremap <silent><C-e> :call NERDTreeToggleEnhanced()<CR>
'''

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'rhysd/accelerated-jk'
hook_add = '''
    nmap j <Plug>(accelerated_jk_gj)
    nmap k <Plug>(accelerated_jk_gk)
'''

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_add = '''
    let g:rustfmt_autosave = 1
    let g:rustfmt_command = "/Users/kamino/.cargo/bin/rustfmt"
'''

[[plugins]]
repo = 'vim-syntastic/syntastic'

