[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_event = "InsertEnter"
hook_add = """
    let g:deoplete#enable_at_startup = 1
"""

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    " let g:NERDTreeQuitOnOpen=1
    let NERDTreeShowHidden=1
    autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
hook_add = '''
    nnoremap <silent><C-e> :NERDTreeTabsToggle<CR>
    let g:nerdtree_tabs_meaningful_tab_names = 1
'''

[[plugins]]
repo = 'myusuf3/numbers.vim'
hook_add = '''
    let g:numbers_exclude = ['nerdtree']
'''

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
hook_add = '''
    set hidden
    set signcolumn=yes
    let g:LanguageClient_autoStart = 1
    let g:LanguageClient_serverCommands = {
        \ 'c': ['clangd', '-compile-commands-dir=' . getcwd() . '/build'],
        \ 'cpp': ['clangd', '-compile-commands-dir=' . getcwd() . '/build'],
        \ 'python': ['pyls'],
        \ 'rust': ['rustup', 'run', 'nightly', 'rls'],
    \ }

    nnoremap <F5> :call LanguageClient_contextMenu()<CR>
    nnoremap <silent> K :call LanguageClient#textDocument_hover()<CR>
    nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>
    nnoremap <silent> <F2> :call LanguageClient#textDocument_rename()<CR>
'''

[[plugins]]
repo = 'rhysd/vim-clang-format'
on_ft = ['c', 'cpp', 'cuda']
hook_add = '''
    let g:clang_format#style_options = {
        \ "BasedOnStyle" : "Google",
        \ "AccessModifierOffset" : -2,
        \ "IndentWidth" : 2,
        \ "TabWidth" : 2,
        \ "UseTab" : "Never",
        \ "Standard" : "C++11",
        \ "ColumnLimit" : 100,
        \ "AllowShortBlocksOnASingleLine" : "true",
        \ "AllowShortIfStatementsOnASingleLine" : "true",
        \ "AllowShortCaseLabelsOnASingleLine" : "true"}
    let g:clang_format#auto_format = 1
    autocmd FileType c setlocal sw=2 sts=2 ts=2 et
'''

[[plugins]]
repo = 'tell-k/vim-autopep8'
on_ft = ['python']
hook_add = '''
    let g:autopep8_on_save = 1
    let g:autopep8_disable_show_diff=1
'''

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_add = '''
let g:rustfmt_autosave = 1
'''

