[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = """
    let g:deoplete#enable_at_startup = 1
"""

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    function! NERDTreeToggleEnhanced()
        if g:NERDTree.IsOpen() && winnr() != g:NERDTree.GetWinNum()
            call g:NERDTree.CursorToTreeWin()
        else
            :NERDTreeToggle
        endif
    endfunction
    nnoremap <silent><C-e> :call NERDTreeToggleEnhanced()<CR>
'''

[[plugins]]
repo = 'myusuf3/numbers.vim'
hook_add = '''
    let g:numbers_exclude = ['nerdtree']
'''

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
hook_add = '''
    set hidden
    set signcolumn=yes
    let g:LanguageClient_autoStart = 1
    let g:LanguageClient_serverCommands = {
        \ 'c': ['clangd-6.0', '-compile-commands-dir=' . getcwd() . '/build'],
        \ 'cpp': ['clangd-6.0', '-compile-commands-dir=' . getcwd() . '/build'],
    \ }

    nnoremap <F5> :call LanguageClient_contextMenu()<CR>
    nnoremap <silent> K :call LanguageClient#textDocument_hover()<CR>
    nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>
    nnoremap <silent> <F2> :call LanguageClient#textDocument_rename()<CR>
'''

[[plugins]]
repo = 'rhysd/vim-clang-format'
hook_add = '''
    let g:clang_format#style_options = {
        \ "AccessModifierOffset" : -4,
        \ "IndentWidth" : 4,
        \ "TabWidth" : 4,
        \ "UseTab" : "Never",
        \ "Standard" : "C++11",
        \ "ColumnLimit" : 100,
        \ "AllowShortBlocksOnASingleLine" : "true",
        \ "AllowShortIfStatementsOnASingleLine" : "true",
        \ "AllowShortCaseLabelsOnASingleLine" : "true"}
    let g:clang_format#auto_format = 1
'''
